/**
 * Cursor Backward Pagination Tests
 *
 * Tests for isBackward query parameter support in cursor pagination
 */
import { describe, it, expect, beforeEach } from 'vitest'
import {
  CursorPaginationManager,
} from '../src/runtime/server/utils/mock/pagination/cursor-manager'
import { getSnapshotStore } from '../src/runtime/server/utils/mock/pagination/snapshot-store'
import type { ItemProvider } from '../src/runtime/server/utils/mock/pagination/interfaces'

// Simple mock ItemProvider for testing
class MockItemProvider implements ItemProvider<{ id: string, name: string }> {
  private modelName: string

  constructor(modelName: string = 'TestModel') {
    this.modelName = modelName
  }

  getIdFieldName(): string {
    return 'id'
  }

  getModelName(): string {
    return this.modelName
  }

  generateItem(index: number, _seed: string): { id: string, name: string } {
    return {
      id: `id-${index}`,
      name: `Item ${index}`,
    }
  }

  generateItemWithId(id: string | number, index: number, _seed: string): { id: string, name: string } {
    return {
      id: String(id),
      name: `Item ${index}`,
    }
  }

  generateId(index: number, _seed: string): string | number {
    return `id-${index}`
  }
}

describe('Cursor Backward Pagination', () => {
  let provider: MockItemProvider
  let manager: CursorPaginationManager<{ id: string, name: string }>

  beforeEach(() => {
    // Clear snapshot store before each test
    const store = getSnapshotStore()
    store.clear()

    provider = new MockItemProvider()
    manager = new CursorPaginationManager(provider)
  })

  describe('isBackward without cursor', () => {
    it('should start from end when isBackward=true and no cursor', () => {
      // Get forward first page
      const forwardResult = manager.getCursorPage('TestModel', {
        limit: 10,
        total: 100,
        seed: 'test',
      })

      // Get backward first page (same snapshot)
      const backwardResult = manager.getCursorPage('TestModel', {
        limit: 10,
        total: 100,
        seed: 'test',
        isBackward: true,
      })

      // Forward starts at index 0, backward starts at index 90
      // IDs are generated by snapshot store (UUIDs), so just check structure
      expect(forwardResult.items.length).toBe(10)
      expect(backwardResult.items.length).toBe(10)

      // Forward should have more items, backward should not
      expect(forwardResult.hasMore).toBe(true)
      expect(forwardResult.hasPrev).toBe(false)

      expect(backwardResult.hasMore).toBe(false)
      expect(backwardResult.hasPrev).toBe(true)

      // The items should be different (different indices)
      expect(forwardResult.items[0].id).not.toBe(backwardResult.items[0].id)
    })

    it('should return first items when isBackward=false (default)', () => {
      const result = manager.getCursorPage('TestModel', {
        limit: 10,
        total: 100,
        seed: 'test',
        isBackward: false,
      })

      expect(result.items.length).toBe(10)
      expect(result.hasPrev).toBe(false)
      expect(result.hasMore).toBe(true)
    })
  })

  describe('isBackward with cursor', () => {
    it('should override cursor direction when isBackward=true', () => {
      // Get first page (forward)
      const firstPage = manager.getCursorPage('TestModel', {
        limit: 10,
        total: 100,
        seed: 'test',
      })

      expect(firstPage.nextCursor).toBeDefined()

      // Use nextCursor but with isBackward=true - should go backward from anchor
      const backwardPage = manager.getCursorPage('TestModel', {
        cursor: firstPage.nextCursor!,
        limit: 10,
        total: 100,
        seed: 'test',
        isBackward: true,
      })

      // With backward direction from anchor at index 9, we go backward
      // startIndex = max(0, 9 - 10) = 0, so we get items 0-9 again
      expect(backwardPage.items.length).toBe(10)
      expect(backwardPage.hasPrev).toBe(false) // At the beginning
    })

    it('should use cursor direction when isBackward=false', () => {
      // Get first page
      const firstPage = manager.getCursorPage('TestModel', {
        limit: 10,
        total: 100,
        seed: 'test',
      })

      // Use nextCursor with isBackward=false - normal forward pagination
      const secondPage = manager.getCursorPage('TestModel', {
        cursor: firstPage.nextCursor!,
        limit: 10,
        total: 100,
        seed: 'test',
        isBackward: false,
      })

      // Should get items 10-19
      expect(secondPage.items.length).toBe(10)
      expect(secondPage.hasPrev).toBe(true)
      expect(secondPage.hasMore).toBe(true)
    })
  })

  describe('getCursorPageWithProvider', () => {
    it('should support isBackward with external provider', () => {
      const externalProvider = new MockItemProvider('ExternalModel')

      // Forward first page
      const forwardResult = manager.getCursorPageWithProvider(externalProvider, {
        limit: 10,
        total: 50,
        seed: 'external',
      })

      // Get backward first page (same snapshot)
      const backwardResult = manager.getCursorPageWithProvider(externalProvider, {
        limit: 10,
        total: 50,
        seed: 'external',
        isBackward: true,
      })

      // Forward starts at index 0, backward starts at index 40
      expect(forwardResult.items.length).toBe(10)
      expect(backwardResult.items.length).toBe(10)

      expect(forwardResult.hasMore).toBe(true)
      expect(backwardResult.hasMore).toBe(false)
    })
  })

  describe('CursorConfig backwardParam', () => {
    it('should have backwardParam in DEFAULT_CURSOR_CONFIG', async () => {
      const { DEFAULT_CURSOR_CONFIG } = await import(
        '../src/runtime/server/utils/mock/pagination/types'
      )

      expect(DEFAULT_CURSOR_CONFIG.backwardParam).toBe('isBackward')
    })

    it('should export CursorConfig with backwardParam type', async () => {
      const { DEFAULT_CURSOR_CONFIG } = await import('../src/runtime/server/utils/mock/pagination/types')

      // Verify the import is valid at runtime
      expect(DEFAULT_CURSOR_CONFIG).toBeDefined()

      // Type check - if this compiles, the type is correct
      const config: typeof DEFAULT_CURSOR_CONFIG = {
        enableExpiry: true,
        cursorTTL: 3600000,
        includeSortInfo: false,
        backwardParam: 'customBackward',
      }

      expect(config.backwardParam).toBe('customBackward')
    })
  })

  describe('CursorPaginationOptions isBackward', () => {
    it('should accept isBackward in options', async () => {
      const { CursorPaginationManager } = await import(
        '../src/runtime/server/utils/mock/pagination/cursor-manager'
      )

      // This test verifies the type accepts isBackward
      const testProvider = new MockItemProvider()
      const testManager = new CursorPaginationManager(testProvider)

      // Should not throw
      const result = testManager.getCursorPage('Test', {
        limit: 5,
        isBackward: true,
      })

      expect(result).toBeDefined()
      expect(result.items).toBeDefined()
    })
  })

  describe('Edge cases', () => {
    it('should handle isBackward with small total', () => {
      const result = manager.getCursorPage('TestModel', {
        limit: 10,
        total: 5,
        seed: 'small',
        isBackward: true,
      })

      // With total=5 and limit=10, starting from end = max(0, 5-10) = 0
      // So all items are returned
      expect(result.items.length).toBe(5)
      expect(result.hasMore).toBe(false)
      expect(result.hasPrev).toBe(false)
    })

    it('should handle isBackward with limit equal to total', () => {
      const result = manager.getCursorPage('TestModel', {
        limit: 100,
        total: 100,
        seed: 'full',
        isBackward: true,
      })

      // Should get all items
      expect(result.items.length).toBe(100)
      expect(result.hasMore).toBe(false)
      expect(result.hasPrev).toBe(false)
    })
  })
})
