/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Activity } from './Activity';
import {
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
    ActivityToJSONTyped,
} from './Activity';

/**
 * 
 * @export
 * @interface ActivityListResponse
 */
export interface ActivityListResponse {
    /**
     * 
     * @type {Array<Activity>}
     * @memberof ActivityListResponse
     */
    items: Array<Activity>;
    /**
     * 
     * @type {string}
     * @memberof ActivityListResponse
     */
    nextCursor?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityListResponse
     */
    prevCursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ActivityListResponse
     */
    hasMore?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ActivityListResponse
     */
    hasPrev?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ActivityListResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the ActivityListResponse interface.
 */
export function instanceOfActivityListResponse(value: object): value is ActivityListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ActivityListResponseFromJSON(json: any): ActivityListResponse {
    return ActivityListResponseFromJSONTyped(json, false);
}

export function ActivityListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ActivityFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'prevCursor': json['prevCursor'] == null ? undefined : json['prevCursor'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
        'hasPrev': json['hasPrev'] == null ? undefined : json['hasPrev'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ActivityListResponseToJSON(json: any): ActivityListResponse {
    return ActivityListResponseToJSONTyped(json, false);
}

export function ActivityListResponseToJSONTyped(value?: ActivityListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ActivityToJSON)),
        'nextCursor': value['nextCursor'],
        'prevCursor': value['prevCursor'],
        'hasMore': value['hasMore'],
        'hasPrev': value['hasPrev'],
        'total': value['total'],
    };
}

