/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    type: ActivityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    description: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Activity
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    userAgent?: string;
}


/**
 * @export
 */
export const ActivityTypeEnum = {
    Login: 'login',
    Logout: 'logout',
    View: 'view',
    Create: 'create',
    Update: 'update',
    Delete: 'delete',
    Share: 'share',
    Comment: 'comment'
} as const;
export type ActivityTypeEnum = typeof ActivityTypeEnum[keyof typeof ActivityTypeEnum];


/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'type': json['type'],
        'description': json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'type': value['type'],
        'description': value['description'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'ipAddress': value['ipAddress'],
        'userAgent': value['userAgent'],
    };
}

