/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminUser
 */
export interface AdminUser {
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    role: AdminUserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    status: AdminUserStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof AdminUser
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUser
     */
    permissions?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AdminUser
     */
    lastLoginIp?: string;
    /**
     * 
     * @type {number}
     * @memberof AdminUser
     */
    loginCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AdminUser
     */
    isSuperAdmin?: boolean;
}


/**
 * @export
 */
export const AdminUserRoleEnum = {
    Admin: 'admin',
    User: 'user',
    Guest: 'guest'
} as const;
export type AdminUserRoleEnum = typeof AdminUserRoleEnum[keyof typeof AdminUserRoleEnum];

/**
 * @export
 */
export const AdminUserStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Suspended: 'suspended'
} as const;
export type AdminUserStatusEnum = typeof AdminUserStatusEnum[keyof typeof AdminUserStatusEnum];


/**
 * Check if a given object implements the AdminUser interface.
 */
export function instanceOfAdminUser(value: object): value is AdminUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminUserFromJSON(json: any): AdminUser {
    return AdminUserFromJSONTyped(json, false);
}

export function AdminUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'role': json['role'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
        'lastLoginIp': json['lastLoginIp'] == null ? undefined : json['lastLoginIp'],
        'loginCount': json['loginCount'] == null ? undefined : json['loginCount'],
        'isSuperAdmin': json['isSuperAdmin'] == null ? undefined : json['isSuperAdmin'],
    };
}

export function AdminUserToJSON(json: any): AdminUser {
    return AdminUserToJSONTyped(json, false);
}

export function AdminUserToJSONTyped(value?: AdminUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'name': value['name'],
        'avatarUrl': value['avatarUrl'],
        'role': value['role'],
        'status': value['status'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'permissions': value['permissions'],
        'lastLoginIp': value['lastLoginIp'],
        'loginCount': value['loginCount'],
        'isSuperAdmin': value['isSuperAdmin'],
    };
}

