/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentInfo } from './PaymentInfo';
import {
    PaymentInfoFromJSON,
    PaymentInfoFromJSONTyped,
    PaymentInfoToJSON,
    PaymentInfoToJSONTyped,
} from './PaymentInfo';
import type { AdvancedOrderItem } from './AdvancedOrderItem';
import {
    AdvancedOrderItemFromJSON,
    AdvancedOrderItemFromJSONTyped,
    AdvancedOrderItemToJSON,
    AdvancedOrderItemToJSONTyped,
} from './AdvancedOrderItem';
import type { ShippingInfo } from './ShippingInfo';
import {
    ShippingInfoFromJSON,
    ShippingInfoFromJSONTyped,
    ShippingInfoToJSON,
    ShippingInfoToJSONTyped,
} from './ShippingInfo';

/**
 * 
 * @export
 * @interface AdvancedOrder
 */
export interface AdvancedOrder {
    /**
     * 
     * @type {string}
     * @memberof AdvancedOrder
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdvancedOrder
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdvancedOrder
     */
    status: AdvancedOrderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AdvancedOrder
     */
    priority: AdvancedOrderPriorityEnum;
    /**
     * 
     * @type {Array<AdvancedOrderItem>}
     * @memberof AdvancedOrder
     */
    items?: Array<AdvancedOrderItem>;
    /**
     * 
     * @type {ShippingInfo}
     * @memberof AdvancedOrder
     */
    shipping?: ShippingInfo;
    /**
     * 
     * @type {PaymentInfo}
     * @memberof AdvancedOrder
     */
    payment?: PaymentInfo;
    /**
     * 
     * @type {Date}
     * @memberof AdvancedOrder
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdvancedOrder
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const AdvancedOrderStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled'
} as const;
export type AdvancedOrderStatusEnum = typeof AdvancedOrderStatusEnum[keyof typeof AdvancedOrderStatusEnum];

/**
 * @export
 */
export const AdvancedOrderPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;
export type AdvancedOrderPriorityEnum = typeof AdvancedOrderPriorityEnum[keyof typeof AdvancedOrderPriorityEnum];


/**
 * Check if a given object implements the AdvancedOrder interface.
 */
export function instanceOfAdvancedOrder(value: object): value is AdvancedOrder {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function AdvancedOrderFromJSON(json: any): AdvancedOrder {
    return AdvancedOrderFromJSONTyped(json, false);
}

export function AdvancedOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancedOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'status': json['status'],
        'priority': json['priority'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AdvancedOrderItemFromJSON)),
        'shipping': json['shipping'] == null ? undefined : ShippingInfoFromJSON(json['shipping']),
        'payment': json['payment'] == null ? undefined : PaymentInfoFromJSON(json['payment']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AdvancedOrderToJSON(json: any): AdvancedOrder {
    return AdvancedOrderToJSONTyped(json, false);
}

export function AdvancedOrderToJSONTyped(value?: AdvancedOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'status': value['status'],
        'priority': value['priority'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AdvancedOrderItemToJSON)),
        'shipping': ShippingInfoToJSON(value['shipping']),
        'payment': PaymentInfoToJSON(value['payment']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

