/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdvancedOrderItem
 */
export interface AdvancedOrderItem {
    /**
     * 
     * @type {string}
     * @memberof AdvancedOrderItem
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdvancedOrderItem
     */
    productName?: string;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderItem
     */
    unitPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderItem
     */
    discount?: number;
}

/**
 * Check if a given object implements the AdvancedOrderItem interface.
 */
export function instanceOfAdvancedOrderItem(value: object): value is AdvancedOrderItem {
    return true;
}

export function AdvancedOrderItemFromJSON(json: any): AdvancedOrderItem {
    return AdvancedOrderItemFromJSONTyped(json, false);
}

export function AdvancedOrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancedOrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
        'discount': json['discount'] == null ? undefined : json['discount'],
    };
}

export function AdvancedOrderItemToJSON(json: any): AdvancedOrderItem {
    return AdvancedOrderItemToJSONTyped(json, false);
}

export function AdvancedOrderItemToJSONTyped(value?: AdvancedOrderItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'productName': value['productName'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
        'discount': value['discount'],
    };
}

