/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvancedOrder } from './AdvancedOrder';
import {
    AdvancedOrderFromJSON,
    AdvancedOrderFromJSONTyped,
    AdvancedOrderToJSON,
    AdvancedOrderToJSONTyped,
} from './AdvancedOrder';

/**
 * 
 * @export
 * @interface AdvancedOrderListResponse
 */
export interface AdvancedOrderListResponse {
    /**
     * 
     * @type {Array<AdvancedOrder>}
     * @memberof AdvancedOrderListResponse
     */
    items: Array<AdvancedOrder>;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderListResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderListResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderListResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof AdvancedOrderListResponse
     */
    limit?: number;
}

/**
 * Check if a given object implements the AdvancedOrderListResponse interface.
 */
export function instanceOfAdvancedOrderListResponse(value: object): value is AdvancedOrderListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AdvancedOrderListResponseFromJSON(json: any): AdvancedOrderListResponse {
    return AdvancedOrderListResponseFromJSONTyped(json, false);
}

export function AdvancedOrderListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvancedOrderListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdvancedOrderFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'total': json['total'] == null ? undefined : json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function AdvancedOrderListResponseToJSON(json: any): AdvancedOrderListResponse {
    return AdvancedOrderListResponseToJSONTyped(json, false);
}

export function AdvancedOrderListResponseToJSONTyped(value?: AdvancedOrderListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdvancedOrderToJSON)),
        'page': value['page'],
        'totalPages': value['totalPages'],
        'total': value['total'],
        'limit': value['limit'],
    };
}

