/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllScalarTypes
 */
export interface AllScalarTypes {
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    doubleVal: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    floatVal: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    int32Val: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    int64Val: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    uint32Val: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    uint64Val: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    sint32Val?: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    sint64Val?: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    fixed32Val?: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    fixed64Val?: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    sfixed32Val?: number;
    /**
     * 
     * @type {number}
     * @memberof AllScalarTypes
     */
    sfixed64Val?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AllScalarTypes
     */
    boolVal: boolean;
    /**
     * 
     * @type {string}
     * @memberof AllScalarTypes
     */
    stringVal: string;
    /**
     * 
     * @type {string}
     * @memberof AllScalarTypes
     */
    bytesVal: string;
}

/**
 * Check if a given object implements the AllScalarTypes interface.
 */
export function instanceOfAllScalarTypes(value: object): value is AllScalarTypes {
    if (!('doubleVal' in value) || value['doubleVal'] === undefined) return false;
    if (!('floatVal' in value) || value['floatVal'] === undefined) return false;
    if (!('int32Val' in value) || value['int32Val'] === undefined) return false;
    if (!('int64Val' in value) || value['int64Val'] === undefined) return false;
    if (!('uint32Val' in value) || value['uint32Val'] === undefined) return false;
    if (!('uint64Val' in value) || value['uint64Val'] === undefined) return false;
    if (!('boolVal' in value) || value['boolVal'] === undefined) return false;
    if (!('stringVal' in value) || value['stringVal'] === undefined) return false;
    if (!('bytesVal' in value) || value['bytesVal'] === undefined) return false;
    return true;
}

export function AllScalarTypesFromJSON(json: any): AllScalarTypes {
    return AllScalarTypesFromJSONTyped(json, false);
}

export function AllScalarTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllScalarTypes {
    if (json == null) {
        return json;
    }
    return {
        
        'doubleVal': json['doubleVal'],
        'floatVal': json['floatVal'],
        'int32Val': json['int32Val'],
        'int64Val': json['int64Val'],
        'uint32Val': json['uint32Val'],
        'uint64Val': json['uint64Val'],
        'sint32Val': json['sint32Val'] == null ? undefined : json['sint32Val'],
        'sint64Val': json['sint64Val'] == null ? undefined : json['sint64Val'],
        'fixed32Val': json['fixed32Val'] == null ? undefined : json['fixed32Val'],
        'fixed64Val': json['fixed64Val'] == null ? undefined : json['fixed64Val'],
        'sfixed32Val': json['sfixed32Val'] == null ? undefined : json['sfixed32Val'],
        'sfixed64Val': json['sfixed64Val'] == null ? undefined : json['sfixed64Val'],
        'boolVal': json['boolVal'],
        'stringVal': json['stringVal'],
        'bytesVal': json['bytesVal'],
    };
}

export function AllScalarTypesToJSON(json: any): AllScalarTypes {
    return AllScalarTypesToJSONTyped(json, false);
}

export function AllScalarTypesToJSONTyped(value?: AllScalarTypes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'doubleVal': value['doubleVal'],
        'floatVal': value['floatVal'],
        'int32Val': value['int32Val'],
        'int64Val': value['int64Val'],
        'uint32Val': value['uint32Val'],
        'uint64Val': value['uint64Val'],
        'sint32Val': value['sint32Val'],
        'sint64Val': value['sint64Val'],
        'fixed32Val': value['fixed32Val'],
        'fixed64Val': value['fixed64Val'],
        'sfixed32Val': value['sfixed32Val'],
        'sfixed64Val': value['sfixed64Val'],
        'boolVal': value['boolVal'],
        'stringVal': value['stringVal'],
        'bytesVal': value['bytesVal'],
    };
}

