/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryNode
 */
export interface CategoryNode {
    /**
     * 
     * @type {string}
     * @memberof CategoryNode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryNode
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryNode
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryNode
     */
    parentId?: string | null;
    /**
     * 
     * @type {Array<CategoryNode>}
     * @memberof CategoryNode
     */
    children?: Array<CategoryNode>;
    /**
     * 
     * @type {number}
     * @memberof CategoryNode
     */
    productCount?: number;
}

/**
 * Check if a given object implements the CategoryNode interface.
 */
export function instanceOfCategoryNode(value: object): value is CategoryNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CategoryNodeFromJSON(json: any): CategoryNode {
    return CategoryNodeFromJSONTyped(json, false);
}

export function CategoryNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(CategoryNodeFromJSON)),
        'productCount': json['productCount'] == null ? undefined : json['productCount'],
    };
}

export function CategoryNodeToJSON(json: any): CategoryNode {
    return CategoryNodeToJSONTyped(json, false);
}

export function CategoryNodeToJSONTyped(value?: CategoryNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'parentId': value['parentId'],
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(CategoryNodeToJSON)),
        'productCount': value['productCount'],
    };
}

