/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface CommentListResponse
 */
export interface CommentListResponse {
    /**
     * 
     * @type {Array<Comment>}
     * @memberof CommentListResponse
     */
    items: Array<Comment>;
    /**
     * 
     * @type {number}
     * @memberof CommentListResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the CommentListResponse interface.
 */
export function instanceOfCommentListResponse(value: object): value is CommentListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CommentListResponseFromJSON(json: any): CommentListResponse {
    return CommentListResponseFromJSONTyped(json, false);
}

export function CommentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CommentFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function CommentListResponseToJSON(json: any): CommentListResponse {
    return CommentListResponseToJSONTyped(json, false);
}

export function CommentListResponseToJSONTyped(value?: CommentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CommentToJSON)),
        'total': value['total'],
    };
}

