/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentThread
 */
export interface CommentThread {
    /**
     * 
     * @type {string}
     * @memberof CommentThread
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CommentThread
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CommentThread
     */
    author: string;
    /**
     * 
     * @type {Date}
     * @memberof CommentThread
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof CommentThread
     */
    likes?: number;
    /**
     * 
     * @type {Array<CommentThread>}
     * @memberof CommentThread
     */
    replies?: Array<CommentThread>;
}

/**
 * Check if a given object implements the CommentThread interface.
 */
export function instanceOfCommentThread(value: object): value is CommentThread {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    return true;
}

export function CommentThreadFromJSON(json: any): CommentThread {
    return CommentThreadFromJSONTyped(json, false);
}

export function CommentThreadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentThread {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'author': json['author'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'likes': json['likes'] == null ? undefined : json['likes'],
        'replies': json['replies'] == null ? undefined : ((json['replies'] as Array<any>).map(CommentThreadFromJSON)),
    };
}

export function CommentThreadToJSON(json: any): CommentThread {
    return CommentThreadToJSONTyped(json, false);
}

export function CommentThreadToJSONTyped(value?: CommentThread | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'author': value['author'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'likes': value['likes'],
        'replies': value['replies'] == null ? undefined : ((value['replies'] as Array<any>).map(CommentThreadToJSON)),
    };
}

