/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    postId: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    authorName?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'postId': json['postId'],
        'authorId': json['authorId'],
        'authorName': json['authorName'] == null ? undefined : json['authorName'],
        'content': json['content'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CommentToJSON(json: any): Comment {
    return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'postId': value['postId'],
        'authorId': value['authorId'],
        'authorName': value['authorName'],
        'content': value['content'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

