/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Department } from './Department';
import {
    DepartmentFromJSON,
    DepartmentFromJSONTyped,
    DepartmentToJSON,
    DepartmentToJSONTyped,
} from './Department';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    name: string;
    /**
     * 
     * @type {Address}
     * @memberof Company
     */
    address?: Address;
    /**
     * 
     * @type {Array<Department>}
     * @memberof Company
     */
    departments?: Array<Department>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Company
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): value is Company {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'departments': json['departments'] == null ? undefined : ((json['departments'] as Array<any>).map(DepartmentFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CompanyToJSON(json: any): Company {
    return CompanyToJSONTyped(json, false);
}

export function CompanyToJSONTyped(value?: Company | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': AddressToJSON(value['address']),
        'departments': value['departments'] == null ? undefined : ((value['departments'] as Array<any>).map(DepartmentToJSON)),
        'metadata': value['metadata'],
    };
}

