/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequest
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequest
     */
    category: CreateProductRequestCategoryEnum;
}


/**
 * @export
 */
export const CreateProductRequestCategoryEnum = {
    Electronics: 'electronics',
    Clothing: 'clothing',
    Food: 'food',
    Books: 'books',
    Other: 'other'
} as const;
export type CreateProductRequestCategoryEnum = typeof CreateProductRequestCategoryEnum[keyof typeof CreateProductRequestCategoryEnum];


/**
 * Check if a given object implements the CreateProductRequest interface.
 */
export function instanceOfCreateProductRequest(value: object): value is CreateProductRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CreateProductRequestFromJSON(json: any): CreateProductRequest {
    return CreateProductRequestFromJSONTyped(json, false);
}

export function CreateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'category': json['category'],
    };
}

export function CreateProductRequestToJSON(json: any): CreateProductRequest {
    return CreateProductRequestToJSONTyped(json, false);
}

export function CreateProductRequestToJSONTyped(value?: CreateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'category': value['category'],
    };
}

