/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateOrderRequestItemsInner } from './CreateOrderRequestItemsInner';
import {
    CreateOrderRequestItemsInnerFromJSON,
    CreateOrderRequestItemsInnerFromJSONTyped,
    CreateOrderRequestItemsInnerToJSON,
    CreateOrderRequestItemsInnerToJSONTyped,
} from './CreateOrderRequestItemsInner';

/**
 * 
 * @export
 * @interface CreateOrderRequest
 */
export interface CreateOrderRequest {
    /**
     * 
     * @type {Array<CreateOrderRequestItemsInner>}
     * @memberof CreateOrderRequest
     */
    items: Array<CreateOrderRequestItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequest
     */
    shippingAddress?: string;
}

/**
 * Check if a given object implements the CreateOrderRequest interface.
 */
export function instanceOfCreateOrderRequest(value: object): value is CreateOrderRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CreateOrderRequestFromJSON(json: any): CreateOrderRequest {
    return CreateOrderRequestFromJSONTyped(json, false);
}

export function CreateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CreateOrderRequestItemsInnerFromJSON)),
        'shippingAddress': json['shippingAddress'] == null ? undefined : json['shippingAddress'],
    };
}

export function CreateOrderRequestToJSON(json: any): CreateOrderRequest {
    return CreateOrderRequestToJSONTyped(json, false);
}

export function CreateOrderRequestToJSONTyped(value?: CreateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CreateOrderRequestItemsInnerToJSON)),
        'shippingAddress': value['shippingAddress'],
    };
}

