/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderRequestItemsInner
 */
export interface CreateOrderRequestItemsInner {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestItemsInner
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderRequestItemsInner
     */
    quantity: number;
}

/**
 * Check if a given object implements the CreateOrderRequestItemsInner interface.
 */
export function instanceOfCreateOrderRequestItemsInner(value: object): value is CreateOrderRequestItemsInner {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CreateOrderRequestItemsInnerFromJSON(json: any): CreateOrderRequestItemsInner {
    return CreateOrderRequestItemsInnerFromJSONTyped(json, false);
}

export function CreateOrderRequestItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderRequestItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'quantity': json['quantity'],
    };
}

export function CreateOrderRequestItemsInnerToJSON(json: any): CreateOrderRequestItemsInner {
    return CreateOrderRequestItemsInnerToJSONTyped(json, false);
}

export function CreateOrderRequestItemsInnerToJSONTyped(value?: CreateOrderRequestItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

