/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Employee } from './Employee';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
    EmployeeToJSONTyped,
} from './Employee';

/**
 * 
 * @export
 * @interface Department
 */
export interface Department {
    /**
     * 
     * @type {string}
     * @memberof Department
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Department
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Department
     */
    headCount?: number;
    /**
     * 
     * @type {Employee}
     * @memberof Department
     */
    manager?: Employee;
    /**
     * 
     * @type {Array<Department>}
     * @memberof Department
     */
    subDepartments?: Array<Department>;
}

/**
 * Check if a given object implements the Department interface.
 */
export function instanceOfDepartment(value: object): value is Department {
    return true;
}

export function DepartmentFromJSON(json: any): Department {
    return DepartmentFromJSONTyped(json, false);
}

export function DepartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Department {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'headCount': json['headCount'] == null ? undefined : json['headCount'],
        'manager': json['manager'] == null ? undefined : EmployeeFromJSON(json['manager']),
        'subDepartments': json['subDepartments'] == null ? undefined : ((json['subDepartments'] as Array<any>).map(DepartmentFromJSON)),
    };
}

export function DepartmentToJSON(json: any): Department {
    return DepartmentToJSONTyped(json, false);
}

export function DepartmentToJSONTyped(value?: Department | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'headCount': value['headCount'],
        'manager': EmployeeToJSON(value['manager']),
        'subDepartments': value['subDepartments'] == null ? undefined : ((value['subDepartments'] as Array<any>).map(DepartmentToJSON)),
    };
}

