/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type DynamicConfigValue
 * 
 * @export
 */
export type DynamicConfigValue = boolean | number | string;

export function DynamicConfigValueFromJSON(json: any): DynamicConfigValue {
    return DynamicConfigValueFromJSONTyped(json, false);
}

export function DynamicConfigValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicConfigValue {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'boolean') {
        return json;
    }
    return {} as any;
}

export function DynamicConfigValueToJSON(json: any): any {
    return DynamicConfigValueToJSONTyped(json, false);
}

export function DynamicConfigValueToJSONTyped(value?: DynamicConfigValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'boolean') {
        return value;
    }
    return {};
}

