/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DynamicConfigValue } from './DynamicConfigValue';
import {
    DynamicConfigValueFromJSON,
    DynamicConfigValueFromJSONTyped,
    DynamicConfigValueToJSON,
    DynamicConfigValueToJSONTyped,
} from './DynamicConfigValue';

/**
 * 
 * @export
 * @interface DynamicConfig
 */
export interface DynamicConfig {
    [key: string]: DynamicConfigValue | any;
    /**
     * 
     * @type {string}
     * @memberof DynamicConfig
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicConfig
     */
    environment?: string;
}

/**
 * Check if a given object implements the DynamicConfig interface.
 */
export function instanceOfDynamicConfig(value: object): value is DynamicConfig {
    return true;
}

export function DynamicConfigFromJSON(json: any): DynamicConfig {
    return DynamicConfigFromJSONTyped(json, false);
}

export function DynamicConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicConfig {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'version': json['version'] == null ? undefined : json['version'],
        'environment': json['environment'] == null ? undefined : json['environment'],
    };
}

export function DynamicConfigToJSON(json: any): DynamicConfig {
    return DynamicConfigToJSONTyped(json, false);
}

export function DynamicConfigToJSONTyped(value?: DynamicConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'version': value['version'],
        'environment': value['environment'],
    };
}

