/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailNotification
 */
export interface EmailNotification {
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    type: EmailNotificationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof EmailNotification
     */
    recipientEmail: string;
    /**
     * 
     * @type {Date}
     * @memberof EmailNotification
     */
    sentAt?: Date;
}


/**
 * @export
 */
export const EmailNotificationTypeEnum = {
    Email: 'email'
} as const;
export type EmailNotificationTypeEnum = typeof EmailNotificationTypeEnum[keyof typeof EmailNotificationTypeEnum];


/**
 * Check if a given object implements the EmailNotification interface.
 */
export function instanceOfEmailNotification(value: object): value is EmailNotification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('recipientEmail' in value) || value['recipientEmail'] === undefined) return false;
    return true;
}

export function EmailNotificationFromJSON(json: any): EmailNotification {
    return EmailNotificationFromJSONTyped(json, false);
}

export function EmailNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'subject': json['subject'],
        'body': json['body'],
        'recipientEmail': json['recipientEmail'],
        'sentAt': json['sentAt'] == null ? undefined : (new Date(json['sentAt'])),
    };
}

export function EmailNotificationToJSON(json: any): EmailNotification {
    return EmailNotificationToJSONTyped(json, false);
}

export function EmailNotificationToJSONTyped(value?: EmailNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'subject': value['subject'],
        'body': value['body'],
        'recipientEmail': value['recipientEmail'],
        'sentAt': value['sentAt'] == null ? value['sentAt'] : value['sentAt'].toISOString(),
    };
}

