/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Employee
 */
export interface Employee {
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Employee
     */
    email?: string;
}

/**
 * Check if a given object implements the Employee interface.
 */
export function instanceOfEmployee(value: object): value is Employee {
    return true;
}

export function EmployeeFromJSON(json: any): Employee {
    return EmployeeFromJSONTyped(json, false);
}

export function EmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Employee {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'title': json['title'] == null ? undefined : json['title'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function EmployeeToJSON(json: any): Employee {
    return EmployeeToJSONTyped(json, false);
}

export function EmployeeToJSONTyped(value?: Employee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'email': value['email'],
    };
}

