/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphEdge } from './GraphEdge';
import {
    GraphEdgeFromJSON,
    GraphEdgeFromJSONTyped,
    GraphEdgeToJSON,
    GraphEdgeToJSONTyped,
} from './GraphEdge';

/**
 * 
 * @export
 * @interface GraphNode
 */
export interface GraphNode {
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GraphNode
     */
    label?: string;
    /**
     * 
     * @type {number}
     * @memberof GraphNode
     */
    weight?: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GraphNode
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {Array<GraphEdge>}
     * @memberof GraphNode
     */
    edges?: Array<GraphEdge>;
}

/**
 * Check if a given object implements the GraphNode interface.
 */
export function instanceOfGraphNode(value: object): value is GraphNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GraphNodeFromJSON(json: any): GraphNode {
    return GraphNodeFromJSONTyped(json, false);
}

export function GraphNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'edges': json['edges'] == null ? undefined : ((json['edges'] as Array<any>).map(GraphEdgeFromJSON)),
    };
}

export function GraphNodeToJSON(json: any): GraphNode {
    return GraphNodeToJSONTyped(json, false);
}

export function GraphNodeToJSONTyped(value?: GraphNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'weight': value['weight'],
        'metadata': value['metadata'],
        'edges': value['edges'] == null ? undefined : ((value['edges'] as Array<any>).map(GraphEdgeToJSON)),
    };
}

