/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphEdge
 */
export interface GraphEdge {
    /**
     * 
     * @type {string}
     * @memberof GraphEdge
     */
    targetId?: string;
    /**
     * 
     * @type {number}
     * @memberof GraphEdge
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof GraphEdge
     */
    label?: string;
}

/**
 * Check if a given object implements the GraphEdge interface.
 */
export function instanceOfGraphEdge(value: object): value is GraphEdge {
    return true;
}

export function GraphEdgeFromJSON(json: any): GraphEdge {
    return GraphEdgeFromJSONTyped(json, false);
}

export function GraphEdgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphEdge {
    if (json == null) {
        return json;
    }
    return {
        
        'targetId': json['targetId'] == null ? undefined : json['targetId'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function GraphEdgeToJSON(json: any): GraphEdge {
    return GraphEdgeToJSONTyped(json, false);
}

export function GraphEdgeToJSONTyped(value?: GraphEdge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetId': value['targetId'],
        'weight': value['weight'],
        'label': value['label'],
    };
}

