/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Metrics
 */
export interface Metrics {
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    totalUsers?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    totalRequests?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    activeConnections?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    cpuUsage?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    memoryUsage?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    errorRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    latencyMs?: number;
    /**
     * 
     * @type {number}
     * @memberof Metrics
     */
    throughput?: number;
}

/**
 * Check if a given object implements the Metrics interface.
 */
export function instanceOfMetrics(value: object): value is Metrics {
    return true;
}

export function MetricsFromJSON(json: any): Metrics {
    return MetricsFromJSONTyped(json, false);
}

export function MetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metrics {
    if (json == null) {
        return json;
    }
    return {
        
        'totalUsers': json['totalUsers'] == null ? undefined : json['totalUsers'],
        'totalRequests': json['totalRequests'] == null ? undefined : json['totalRequests'],
        'activeConnections': json['activeConnections'] == null ? undefined : json['activeConnections'],
        'cpuUsage': json['cpuUsage'] == null ? undefined : json['cpuUsage'],
        'memoryUsage': json['memoryUsage'] == null ? undefined : json['memoryUsage'],
        'errorRate': json['errorRate'] == null ? undefined : json['errorRate'],
        'latencyMs': json['latencyMs'] == null ? undefined : json['latencyMs'],
        'throughput': json['throughput'] == null ? undefined : json['throughput'],
    };
}

export function MetricsToJSON(json: any): Metrics {
    return MetricsToJSONTyped(json, false);
}

export function MetricsToJSONTyped(value?: Metrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalUsers': value['totalUsers'],
        'totalRequests': value['totalRequests'],
        'activeConnections': value['activeConnections'],
        'cpuUsage': value['cpuUsage'],
        'memoryUsage': value['memoryUsage'],
        'errorRate': value['errorRate'],
        'latencyMs': value['latencyMs'],
        'throughput': value['throughput'],
    };
}

