/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationSettings
 */
export interface NotificationSettings {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationSettings
     */
    email?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationSettings
     */
    push?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationSettings
     */
    sms?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationSettings
     */
    frequency?: NotificationSettingsFrequencyEnum;
}


/**
 * @export
 */
export const NotificationSettingsFrequencyEnum = {
    Immediate: 'immediate',
    Hourly: 'hourly',
    Daily: 'daily',
    Weekly: 'weekly'
} as const;
export type NotificationSettingsFrequencyEnum = typeof NotificationSettingsFrequencyEnum[keyof typeof NotificationSettingsFrequencyEnum];


/**
 * Check if a given object implements the NotificationSettings interface.
 */
export function instanceOfNotificationSettings(value: object): value is NotificationSettings {
    return true;
}

export function NotificationSettingsFromJSON(json: any): NotificationSettings {
    return NotificationSettingsFromJSONTyped(json, false);
}

export function NotificationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'push': json['push'] == null ? undefined : json['push'],
        'sms': json['sms'] == null ? undefined : json['sms'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
    };
}

export function NotificationSettingsToJSON(json: any): NotificationSettings {
    return NotificationSettingsToJSONTyped(json, false);
}

export function NotificationSettingsToJSONTyped(value?: NotificationSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'push': value['push'],
        'sms': value['sms'],
        'frequency': value['frequency'],
    };
}

