/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EmailNotification } from './EmailNotification';
import {
    instanceOfEmailNotification,
    EmailNotificationFromJSON,
    EmailNotificationFromJSONTyped,
    EmailNotificationToJSON,
} from './EmailNotification';
import type { PushNotification } from './PushNotification';
import {
    instanceOfPushNotification,
    PushNotificationFromJSON,
    PushNotificationFromJSONTyped,
    PushNotificationToJSON,
} from './PushNotification';
import type { SmsNotification } from './SmsNotification';
import {
    instanceOfSmsNotification,
    SmsNotificationFromJSON,
    SmsNotificationFromJSONTyped,
    SmsNotificationToJSON,
} from './SmsNotification';

/**
 * @type Notification
 * 
 * @export
 */
export type Notification = EmailNotification | PushNotification | SmsNotification;

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        default:
            return json;
    }
}

export function NotificationToJSON(json: any): any {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        default:
            return value;
    }
}

