/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface OrderListResponse
 */
export interface OrderListResponse {
    /**
     * 
     * @type {Array<Order>}
     * @memberof OrderListResponse
     */
    items: Array<Order>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof OrderListResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the OrderListResponse interface.
 */
export function instanceOfOrderListResponse(value: object): value is OrderListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function OrderListResponseFromJSON(json: any): OrderListResponse {
    return OrderListResponseFromJSONTyped(json, false);
}

export function OrderListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrderFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function OrderListResponseToJSON(json: any): OrderListResponse {
    return OrderListResponseToJSONTyped(json, false);
}

export function OrderListResponseToJSONTyped(value?: OrderListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrderToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

