/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgMember
 */
export interface OrgMember {
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgMember
     */
    email?: string;
    /**
     * 
     * @type {Array<OrgMember>}
     * @memberof OrgMember
     */
    directReports?: Array<OrgMember>;
}

/**
 * Check if a given object implements the OrgMember interface.
 */
export function instanceOfOrgMember(value: object): value is OrgMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function OrgMemberFromJSON(json: any): OrgMember {
    return OrgMemberFromJSONTyped(json, false);
}

export function OrgMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'department': json['department'] == null ? undefined : json['department'],
        'email': json['email'] == null ? undefined : json['email'],
        'directReports': json['directReports'] == null ? undefined : ((json['directReports'] as Array<any>).map(OrgMemberFromJSON)),
    };
}

export function OrgMemberToJSON(json: any): OrgMember {
    return OrgMemberToJSONTyped(json, false);
}

export function OrgMemberToJSONTyped(value?: OrgMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'department': value['department'],
        'email': value['email'],
        'directReports': value['directReports'] == null ? undefined : ((value['directReports'] as Array<any>).map(OrgMemberToJSON)),
    };
}

