/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'limit': json['limit'],
        'total': json['total'],
        'totalPages': json['totalPages'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

