/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentInfo
 */
export interface PaymentInfo {
    /**
     * 
     * @type {string}
     * @memberof PaymentInfo
     */
    method?: PaymentInfoMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentInfo
     */
    status?: PaymentInfoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PaymentInfo
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentInfo
     */
    currency?: string;
}


/**
 * @export
 */
export const PaymentInfoMethodEnum = {
    CreditCard: 'credit_card',
    DebitCard: 'debit_card',
    Paypal: 'paypal',
    BankTransfer: 'bank_transfer',
    Crypto: 'crypto'
} as const;
export type PaymentInfoMethodEnum = typeof PaymentInfoMethodEnum[keyof typeof PaymentInfoMethodEnum];

/**
 * @export
 */
export const PaymentInfoStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed',
    Refunded: 'refunded'
} as const;
export type PaymentInfoStatusEnum = typeof PaymentInfoStatusEnum[keyof typeof PaymentInfoStatusEnum];


/**
 * Check if a given object implements the PaymentInfo interface.
 */
export function instanceOfPaymentInfo(value: object): value is PaymentInfo {
    return true;
}

export function PaymentInfoFromJSON(json: any): PaymentInfo {
    return PaymentInfoFromJSONTyped(json, false);
}

export function PaymentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'] == null ? undefined : json['method'],
        'status': json['status'] == null ? undefined : json['status'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function PaymentInfoToJSON(json: any): PaymentInfo {
    return PaymentInfoToJSONTyped(json, false);
}

export function PaymentInfoToJSONTyped(value?: PaymentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'status': value['status'],
        'amount': value['amount'],
        'currency': value['currency'],
    };
}

