/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ping200Response
 */
export interface Ping200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Ping200Response
     */
    pong?: boolean;
}

/**
 * Check if a given object implements the Ping200Response interface.
 */
export function instanceOfPing200Response(value: object): value is Ping200Response {
    return true;
}

export function Ping200ResponseFromJSON(json: any): Ping200Response {
    return Ping200ResponseFromJSONTyped(json, false);
}

export function Ping200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ping200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pong': json['pong'] == null ? undefined : json['pong'],
    };
}

export function Ping200ResponseToJSON(json: any): Ping200Response {
    return Ping200ResponseToJSONTyped(json, false);
}

export function Ping200ResponseToJSONTyped(value?: Ping200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pong': value['pong'],
    };
}

