/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
    PostToJSONTyped,
} from './Post';

/**
 * 
 * @export
 * @interface PostListResponse
 */
export interface PostListResponse {
    /**
     * 
     * @type {Array<Post>}
     * @memberof PostListResponse
     */
    items: Array<Post>;
    /**
     * 
     * @type {string}
     * @memberof PostListResponse
     */
    nextCursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostListResponse
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the PostListResponse interface.
 */
export function instanceOfPostListResponse(value: object): value is PostListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PostListResponseFromJSON(json: any): PostListResponse {
    return PostListResponseFromJSONTyped(json, false);
}

export function PostListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PostFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function PostListResponseToJSON(json: any): PostListResponse {
    return PostListResponseToJSONTyped(json, false);
}

export function PostListResponseToJSONTyped(value?: PostListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PostToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

