/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    authorId: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    authorName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Post
     */
    tags?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Post
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Post
     */
    likeCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Post
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Post
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'content': json['content'],
        'authorId': json['authorId'],
        'authorName': json['authorName'] == null ? undefined : json['authorName'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'viewCount': json['viewCount'] == null ? undefined : json['viewCount'],
        'likeCount': json['likeCount'] == null ? undefined : json['likeCount'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PostToJSON(json: any): Post {
    return PostToJSONTyped(json, false);
}

export function PostToJSONTyped(value?: Post | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'authorId': value['authorId'],
        'authorName': value['authorName'],
        'tags': value['tags'],
        'viewCount': value['viewCount'],
        'likeCount': value['likeCount'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

