/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivacySettings
 */
export interface PrivacySettings {
    /**
     * 
     * @type {boolean}
     * @memberof PrivacySettings
     */
    profileVisible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PrivacySettings
     */
    showEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PrivacySettings
     */
    showPhone?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PrivacySettings
     */
    dataSharing?: boolean;
}

/**
 * Check if a given object implements the PrivacySettings interface.
 */
export function instanceOfPrivacySettings(value: object): value is PrivacySettings {
    return true;
}

export function PrivacySettingsFromJSON(json: any): PrivacySettings {
    return PrivacySettingsFromJSONTyped(json, false);
}

export function PrivacySettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacySettings {
    if (json == null) {
        return json;
    }
    return {
        
        'profileVisible': json['profileVisible'] == null ? undefined : json['profileVisible'],
        'showEmail': json['showEmail'] == null ? undefined : json['showEmail'],
        'showPhone': json['showPhone'] == null ? undefined : json['showPhone'],
        'dataSharing': json['dataSharing'] == null ? undefined : json['dataSharing'],
    };
}

export function PrivacySettingsToJSON(json: any): PrivacySettings {
    return PrivacySettingsToJSONTyped(json, false);
}

export function PrivacySettingsToJSONTyped(value?: PrivacySettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profileVisible': value['profileVisible'],
        'showEmail': value['showEmail'],
        'showPhone': value['showPhone'],
        'dataSharing': value['dataSharing'],
    };
}

