/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductVariant
 */
export interface ProductVariant {
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    sku?: string;
}

/**
 * Check if a given object implements the ProductVariant interface.
 */
export function instanceOfProductVariant(value: object): value is ProductVariant {
    return true;
}

export function ProductVariantFromJSON(json: any): ProductVariant {
    return ProductVariantFromJSONTyped(json, false);
}

export function ProductVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'sku': json['sku'] == null ? undefined : json['sku'],
    };
}

export function ProductVariantToJSON(json: any): ProductVariant {
    return ProductVariantToJSONTyped(json, false);
}

export function ProductVariantToJSONTyped(value?: ProductVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'sku': value['sku'],
    };
}

