/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface ProductListResponse
 */
export interface ProductListResponse {
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductListResponse
     */
    items: Array<Product>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ProductListResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the ProductListResponse interface.
 */
export function instanceOfProductListResponse(value: object): value is ProductListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ProductListResponseFromJSON(json: any): ProductListResponse {
    return ProductListResponseFromJSONTyped(json, false);
}

export function ProductListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function ProductListResponseToJSON(json: any): ProductListResponse {
    return ProductListResponseToJSONTyped(json, false);
}

export function ProductListResponseToJSONTyped(value?: ProductListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

