/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductVariant } from './ProductVariant';
import {
    ProductVariantFromJSON,
    ProductVariantFromJSONTyped,
    ProductVariantToJSON,
    ProductVariantToJSONTyped,
} from './ProductVariant';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    category: ProductCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    inStock?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    stockCount?: number;
    /**
     * 
     * @type {Array<ProductVariant>}
     * @memberof Product
     */
    variants?: Array<ProductVariant>;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ProductCategoryEnum = {
    Electronics: 'electronics',
    Clothing: 'clothing',
    Food: 'food',
    Books: 'books',
    Other: 'other'
} as const;
export type ProductCategoryEnum = typeof ProductCategoryEnum[keyof typeof ProductCategoryEnum];


/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'category': json['category'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'inStock': json['inStock'] == null ? undefined : json['inStock'],
        'stockCount': json['stockCount'] == null ? undefined : json['stockCount'],
        'variants': json['variants'] == null ? undefined : ((json['variants'] as Array<any>).map(ProductVariantFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'currency': value['currency'],
        'category': value['category'],
        'imageUrl': value['imageUrl'],
        'inStock': value['inStock'],
        'stockCount': value['stockCount'],
        'variants': value['variants'] == null ? undefined : ((value['variants'] as Array<any>).map(ProductVariantToJSON)),
        'createdAt': value['createdAt'].toISOString(),
    };
}

