/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PushNotification
 */
export interface PushNotification {
    /**
     * 
     * @type {string}
     * @memberof PushNotification
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PushNotification
     */
    type: PushNotificationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PushNotification
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PushNotification
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof PushNotification
     */
    deviceToken: string;
    /**
     * 
     * @type {number}
     * @memberof PushNotification
     */
    badge?: number;
    /**
     * 
     * @type {string}
     * @memberof PushNotification
     */
    sound?: string;
}


/**
 * @export
 */
export const PushNotificationTypeEnum = {
    Push: 'push'
} as const;
export type PushNotificationTypeEnum = typeof PushNotificationTypeEnum[keyof typeof PushNotificationTypeEnum];


/**
 * Check if a given object implements the PushNotification interface.
 */
export function instanceOfPushNotification(value: object): value is PushNotification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('deviceToken' in value) || value['deviceToken'] === undefined) return false;
    return true;
}

export function PushNotificationFromJSON(json: any): PushNotification {
    return PushNotificationFromJSONTyped(json, false);
}

export function PushNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'title': json['title'],
        'message': json['message'],
        'deviceToken': json['deviceToken'],
        'badge': json['badge'] == null ? undefined : json['badge'],
        'sound': json['sound'] == null ? undefined : json['sound'],
    };
}

export function PushNotificationToJSON(json: any): PushNotification {
    return PushNotificationToJSONTyped(json, false);
}

export function PushNotificationToJSONTyped(value?: PushNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'title': value['title'],
        'message': value['message'],
        'deviceToken': value['deviceToken'],
        'badge': value['badge'],
        'sound': value['sound'],
    };
}

