/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportSectionsInner } from './ReportSectionsInner';
import {
    ReportSectionsInnerFromJSON,
    ReportSectionsInnerFromJSONTyped,
    ReportSectionsInnerToJSON,
    ReportSectionsInnerToJSONTyped,
} from './ReportSectionsInner';
import type { ReportMetadata } from './ReportMetadata';
import {
    ReportMetadataFromJSON,
    ReportMetadataFromJSONTyped,
    ReportMetadataToJSON,
    ReportMetadataToJSONTyped,
} from './ReportMetadata';

/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    title: string;
    /**
     * 
     * @type {ReportMetadata}
     * @memberof Report
     */
    metadata: ReportMetadata;
    /**
     * 
     * @type {Array<ReportSectionsInner>}
     * @memberof Report
     */
    sections: Array<ReportSectionsInner>;
}

/**
 * Check if a given object implements the Report interface.
 */
export function instanceOfReport(value: object): value is Report {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('sections' in value) || value['sections'] === undefined) return false;
    return true;
}

export function ReportFromJSON(json: any): Report {
    return ReportFromJSONTyped(json, false);
}

export function ReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Report {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'metadata': ReportMetadataFromJSON(json['metadata']),
        'sections': ((json['sections'] as Array<any>).map(ReportSectionsInnerFromJSON)),
    };
}

export function ReportToJSON(json: any): Report {
    return ReportToJSONTyped(json, false);
}

export function ReportToJSONTyped(value?: Report | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'metadata': ReportMetadataToJSON(value['metadata']),
        'sections': ((value['sections'] as Array<any>).map(ReportSectionsInnerToJSON)),
    };
}

