/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportMetadataAuthorDepartmentOrganization } from './ReportMetadataAuthorDepartmentOrganization';
import {
    ReportMetadataAuthorDepartmentOrganizationFromJSON,
    ReportMetadataAuthorDepartmentOrganizationFromJSONTyped,
    ReportMetadataAuthorDepartmentOrganizationToJSON,
    ReportMetadataAuthorDepartmentOrganizationToJSONTyped,
} from './ReportMetadataAuthorDepartmentOrganization';

/**
 * 
 * @export
 * @interface ReportMetadataAuthorDepartment
 */
export interface ReportMetadataAuthorDepartment {
    /**
     * 
     * @type {string}
     * @memberof ReportMetadataAuthorDepartment
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportMetadataAuthorDepartment
     */
    name?: string;
    /**
     * 
     * @type {ReportMetadataAuthorDepartmentOrganization}
     * @memberof ReportMetadataAuthorDepartment
     */
    organization?: ReportMetadataAuthorDepartmentOrganization;
}

/**
 * Check if a given object implements the ReportMetadataAuthorDepartment interface.
 */
export function instanceOfReportMetadataAuthorDepartment(value: object): value is ReportMetadataAuthorDepartment {
    return true;
}

export function ReportMetadataAuthorDepartmentFromJSON(json: any): ReportMetadataAuthorDepartment {
    return ReportMetadataAuthorDepartmentFromJSONTyped(json, false);
}

export function ReportMetadataAuthorDepartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportMetadataAuthorDepartment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'organization': json['organization'] == null ? undefined : ReportMetadataAuthorDepartmentOrganizationFromJSON(json['organization']),
    };
}

export function ReportMetadataAuthorDepartmentToJSON(json: any): ReportMetadataAuthorDepartment {
    return ReportMetadataAuthorDepartmentToJSONTyped(json, false);
}

export function ReportMetadataAuthorDepartmentToJSONTyped(value?: ReportMetadataAuthorDepartment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'organization': ReportMetadataAuthorDepartmentOrganizationToJSON(value['organization']),
    };
}

