/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportSectionsInnerSubsectionsInner } from './ReportSectionsInnerSubsectionsInner';
import {
    ReportSectionsInnerSubsectionsInnerFromJSON,
    ReportSectionsInnerSubsectionsInnerFromJSONTyped,
    ReportSectionsInnerSubsectionsInnerToJSON,
    ReportSectionsInnerSubsectionsInnerToJSONTyped,
} from './ReportSectionsInnerSubsectionsInner';

/**
 * 
 * @export
 * @interface ReportSectionsInner
 */
export interface ReportSectionsInner {
    /**
     * 
     * @type {string}
     * @memberof ReportSectionsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportSectionsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportSectionsInner
     */
    content?: string;
    /**
     * 
     * @type {Array<ReportSectionsInnerSubsectionsInner>}
     * @memberof ReportSectionsInner
     */
    subsections?: Array<ReportSectionsInnerSubsectionsInner>;
}

/**
 * Check if a given object implements the ReportSectionsInner interface.
 */
export function instanceOfReportSectionsInner(value: object): value is ReportSectionsInner {
    return true;
}

export function ReportSectionsInnerFromJSON(json: any): ReportSectionsInner {
    return ReportSectionsInnerFromJSONTyped(json, false);
}

export function ReportSectionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportSectionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'subsections': json['subsections'] == null ? undefined : ((json['subsections'] as Array<any>).map(ReportSectionsInnerSubsectionsInnerFromJSON)),
    };
}

export function ReportSectionsInnerToJSON(json: any): ReportSectionsInner {
    return ReportSectionsInnerToJSONTyped(json, false);
}

export function ReportSectionsInnerToJSONTyped(value?: ReportSectionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'subsections': value['subsections'] == null ? undefined : ((value['subsections'] as Array<any>).map(ReportSectionsInnerSubsectionsInnerToJSON)),
    };
}

