/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportSectionsInnerSubsectionsInner
 */
export interface ReportSectionsInnerSubsectionsInner {
    /**
     * 
     * @type {string}
     * @memberof ReportSectionsInnerSubsectionsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportSectionsInnerSubsectionsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportSectionsInnerSubsectionsInner
     */
    content?: string;
}

/**
 * Check if a given object implements the ReportSectionsInnerSubsectionsInner interface.
 */
export function instanceOfReportSectionsInnerSubsectionsInner(value: object): value is ReportSectionsInnerSubsectionsInner {
    return true;
}

export function ReportSectionsInnerSubsectionsInnerFromJSON(json: any): ReportSectionsInnerSubsectionsInner {
    return ReportSectionsInnerSubsectionsInnerFromJSONTyped(json, false);
}

export function ReportSectionsInnerSubsectionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportSectionsInnerSubsectionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function ReportSectionsInnerSubsectionsInnerToJSON(json: any): ReportSectionsInnerSubsectionsInner {
    return ReportSectionsInnerSubsectionsInnerToJSONTyped(json, false);
}

export function ReportSectionsInnerSubsectionsInnerToJSONTyped(value?: ReportSectionsInnerSubsectionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
    };
}

