/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportMetadataAuthorDepartment } from './ReportMetadataAuthorDepartment';
import {
    ReportMetadataAuthorDepartmentFromJSON,
    ReportMetadataAuthorDepartmentFromJSONTyped,
    ReportMetadataAuthorDepartmentToJSON,
    ReportMetadataAuthorDepartmentToJSONTyped,
} from './ReportMetadataAuthorDepartment';

/**
 * 
 * @export
 * @interface ReportMetadataAuthor
 */
export interface ReportMetadataAuthor {
    /**
     * 
     * @type {string}
     * @memberof ReportMetadataAuthor
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportMetadataAuthor
     */
    name?: string;
    /**
     * 
     * @type {ReportMetadataAuthorDepartment}
     * @memberof ReportMetadataAuthor
     */
    department?: ReportMetadataAuthorDepartment;
}

/**
 * Check if a given object implements the ReportMetadataAuthor interface.
 */
export function instanceOfReportMetadataAuthor(value: object): value is ReportMetadataAuthor {
    return true;
}

export function ReportMetadataAuthorFromJSON(json: any): ReportMetadataAuthor {
    return ReportMetadataAuthorFromJSONTyped(json, false);
}

export function ReportMetadataAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportMetadataAuthor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'department': json['department'] == null ? undefined : ReportMetadataAuthorDepartmentFromJSON(json['department']),
    };
}

export function ReportMetadataAuthorToJSON(json: any): ReportMetadataAuthor {
    return ReportMetadataAuthorToJSONTyped(json, false);
}

export function ReportMetadataAuthorToJSONTyped(value?: ReportMetadataAuthor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'department': ReportMetadataAuthorDepartmentToJSON(value['department']),
    };
}

