/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportMetadataAuthor } from './ReportMetadataAuthor';
import {
    ReportMetadataAuthorFromJSON,
    ReportMetadataAuthorFromJSONTyped,
    ReportMetadataAuthorToJSON,
    ReportMetadataAuthorToJSONTyped,
} from './ReportMetadataAuthor';

/**
 * 
 * @export
 * @interface ReportMetadata
 */
export interface ReportMetadata {
    /**
     * 
     * @type {ReportMetadataAuthor}
     * @memberof ReportMetadata
     */
    author?: ReportMetadataAuthor;
    /**
     * 
     * @type {Date}
     * @memberof ReportMetadata
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof ReportMetadata
     */
    version?: number;
}

/**
 * Check if a given object implements the ReportMetadata interface.
 */
export function instanceOfReportMetadata(value: object): value is ReportMetadata {
    return true;
}

export function ReportMetadataFromJSON(json: any): ReportMetadata {
    return ReportMetadataFromJSONTyped(json, false);
}

export function ReportMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : ReportMetadataAuthorFromJSON(json['author']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ReportMetadataToJSON(json: any): ReportMetadata {
    return ReportMetadataToJSONTyped(json, false);
}

export function ReportMetadataToJSONTyped(value?: ReportMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': ReportMetadataAuthorToJSON(value['author']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'version': value['version'],
    };
}

