/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportMetadataAuthorDepartmentOrganization
 */
export interface ReportMetadataAuthorDepartmentOrganization {
    /**
     * 
     * @type {string}
     * @memberof ReportMetadataAuthorDepartmentOrganization
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportMetadataAuthorDepartmentOrganization
     */
    name?: string;
}

/**
 * Check if a given object implements the ReportMetadataAuthorDepartmentOrganization interface.
 */
export function instanceOfReportMetadataAuthorDepartmentOrganization(value: object): value is ReportMetadataAuthorDepartmentOrganization {
    return true;
}

export function ReportMetadataAuthorDepartmentOrganizationFromJSON(json: any): ReportMetadataAuthorDepartmentOrganization {
    return ReportMetadataAuthorDepartmentOrganizationFromJSONTyped(json, false);
}

export function ReportMetadataAuthorDepartmentOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportMetadataAuthorDepartmentOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ReportMetadataAuthorDepartmentOrganizationToJSON(json: any): ReportMetadataAuthorDepartmentOrganization {
    return ReportMetadataAuthorDepartmentOrganizationToJSONTyped(json, false);
}

export function ReportMetadataAuthorDepartmentOrganizationToJSONTyped(value?: ReportMetadataAuthorDepartmentOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

