/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * 
     * @type {string}
     * @memberof Settings
     */
    displayName?: string;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    volume?: number;
    /**
     * 
     * @type {number}
     * @memberof Settings
     */
    brightness?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Settings
     */
    favoriteColors?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Settings
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Settings
     */
    theme?: SettingsThemeEnum;
    /**
     * 
     * @type {string}
     * @memberof Settings
     */
    language?: SettingsLanguageEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Settings
     */
    notificationsEnabled?: boolean;
}


/**
 * @export
 */
export const SettingsThemeEnum = {
    Light: 'light',
    Dark: 'dark',
    System: 'system'
} as const;
export type SettingsThemeEnum = typeof SettingsThemeEnum[keyof typeof SettingsThemeEnum];

/**
 * @export
 */
export const SettingsLanguageEnum = {
    Ko: 'ko',
    En: 'en',
    Ja: 'ja',
    Zh: 'zh'
} as const;
export type SettingsLanguageEnum = typeof SettingsLanguageEnum[keyof typeof SettingsLanguageEnum];


/**
 * Check if a given object implements the Settings interface.
 */
export function instanceOfSettings(value: object): value is Settings {
    return true;
}

export function SettingsFromJSON(json: any): Settings {
    return SettingsFromJSONTyped(json, false);
}

export function SettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Settings {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'brightness': json['brightness'] == null ? undefined : json['brightness'],
        'favoriteColors': json['favoriteColors'] == null ? undefined : json['favoriteColors'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'language': json['language'] == null ? undefined : json['language'],
        'notificationsEnabled': json['notificationsEnabled'] == null ? undefined : json['notificationsEnabled'],
    };
}

export function SettingsToJSON(json: any): Settings {
    return SettingsToJSONTyped(json, false);
}

export function SettingsToJSONTyped(value?: Settings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'volume': value['volume'],
        'brightness': value['brightness'],
        'favoriteColors': value['favoriteColors'],
        'phoneNumber': value['phoneNumber'],
        'theme': value['theme'],
        'language': value['language'],
        'notificationsEnabled': value['notificationsEnabled'],
    };
}

