/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface ShippingInfo
 */
export interface ShippingInfo {
    /**
     * 
     * @type {string}
     * @memberof ShippingInfo
     */
    method?: ShippingInfoMethodEnum;
    /**
     * 
     * @type {Address}
     * @memberof ShippingInfo
     */
    address?: Address;
    /**
     * 
     * @type {Date}
     * @memberof ShippingInfo
     */
    estimatedDelivery?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShippingInfo
     */
    trackingNumber?: string;
}


/**
 * @export
 */
export const ShippingInfoMethodEnum = {
    Standard: 'standard',
    Express: 'express',
    Overnight: 'overnight',
    Pickup: 'pickup'
} as const;
export type ShippingInfoMethodEnum = typeof ShippingInfoMethodEnum[keyof typeof ShippingInfoMethodEnum];


/**
 * Check if a given object implements the ShippingInfo interface.
 */
export function instanceOfShippingInfo(value: object): value is ShippingInfo {
    return true;
}

export function ShippingInfoFromJSON(json: any): ShippingInfo {
    return ShippingInfoFromJSONTyped(json, false);
}

export function ShippingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'] == null ? undefined : json['method'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'estimatedDelivery': json['estimatedDelivery'] == null ? undefined : (new Date(json['estimatedDelivery'])),
        'trackingNumber': json['trackingNumber'] == null ? undefined : json['trackingNumber'],
    };
}

export function ShippingInfoToJSON(json: any): ShippingInfo {
    return ShippingInfoToJSONTyped(json, false);
}

export function ShippingInfoToJSONTyped(value?: ShippingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'address': AddressToJSON(value['address']),
        'estimatedDelivery': value['estimatedDelivery'] == null ? value['estimatedDelivery'] : value['estimatedDelivery'].toISOString().substring(0,10),
        'trackingNumber': value['trackingNumber'],
    };
}

