/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsNotification
 */
export interface SmsNotification {
    /**
     * 
     * @type {string}
     * @memberof SmsNotification
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SmsNotification
     */
    type: SmsNotificationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SmsNotification
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof SmsNotification
     */
    phoneNumber: string;
}


/**
 * @export
 */
export const SmsNotificationTypeEnum = {
    Sms: 'sms'
} as const;
export type SmsNotificationTypeEnum = typeof SmsNotificationTypeEnum[keyof typeof SmsNotificationTypeEnum];


/**
 * Check if a given object implements the SmsNotification interface.
 */
export function instanceOfSmsNotification(value: object): value is SmsNotification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    return true;
}

export function SmsNotificationFromJSON(json: any): SmsNotification {
    return SmsNotificationFromJSONTyped(json, false);
}

export function SmsNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'message': json['message'],
        'phoneNumber': json['phoneNumber'],
    };
}

export function SmsNotificationToJSON(json: any): SmsNotification {
    return SmsNotificationToJSONTyped(json, false);
}

export function SmsNotificationToJSONTyped(value?: SmsNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'message': value['message'],
        'phoneNumber': value['phoneNumber'],
    };
}

