/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TreeNode
 */
export interface TreeNode {
    /**
     * 
     * @type {string}
     * @memberof TreeNode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TreeNode
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TreeNode
     */
    value?: string;
    /**
     * 
     * @type {Array<TreeNode>}
     * @memberof TreeNode
     */
    children?: Array<TreeNode>;
}

/**
 * Check if a given object implements the TreeNode interface.
 */
export function instanceOfTreeNode(value: object): value is TreeNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TreeNodeFromJSON(json: any): TreeNode {
    return TreeNodeFromJSONTyped(json, false);
}

export function TreeNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(TreeNodeFromJSON)),
    };
}

export function TreeNodeToJSON(json: any): TreeNode {
    return TreeNodeToJSONTyped(json, false);
}

export function TreeNodeToJSONTyped(value?: TreeNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'value': value['value'],
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(TreeNodeToJSON)),
    };
}

