/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileSocialLinks
 */
export interface UserProfileSocialLinks {
    /**
     * 
     * @type {string}
     * @memberof UserProfileSocialLinks
     */
    twitter?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileSocialLinks
     */
    github?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileSocialLinks
     */
    linkedin?: string;
}

/**
 * Check if a given object implements the UserProfileSocialLinks interface.
 */
export function instanceOfUserProfileSocialLinks(value: object): value is UserProfileSocialLinks {
    return true;
}

export function UserProfileSocialLinksFromJSON(json: any): UserProfileSocialLinks {
    return UserProfileSocialLinksFromJSONTyped(json, false);
}

export function UserProfileSocialLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileSocialLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'twitter': json['twitter'] == null ? undefined : json['twitter'],
        'github': json['github'] == null ? undefined : json['github'],
        'linkedin': json['linkedin'] == null ? undefined : json['linkedin'],
    };
}

export function UserProfileSocialLinksToJSON(json: any): UserProfileSocialLinks {
    return UserProfileSocialLinksToJSONTyped(json, false);
}

export function UserProfileSocialLinksToJSONTyped(value?: UserProfileSocialLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'twitter': value['twitter'],
        'github': value['github'],
        'linkedin': value['linkedin'],
    };
}

