/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivacySettings } from './PrivacySettings';
import {
    PrivacySettingsFromJSON,
    PrivacySettingsFromJSONTyped,
    PrivacySettingsToJSON,
    PrivacySettingsToJSONTyped,
} from './PrivacySettings';
import type { NotificationSettings } from './NotificationSettings';
import {
    NotificationSettingsFromJSON,
    NotificationSettingsFromJSONTyped,
    NotificationSettingsToJSON,
    NotificationSettingsToJSONTyped,
} from './NotificationSettings';

/**
 * 
 * @export
 * @interface UserPreferences
 */
export interface UserPreferences {
    /**
     * 
     * @type {string}
     * @memberof UserPreferences
     */
    theme?: UserPreferencesThemeEnum;
    /**
     * 
     * @type {string}
     * @memberof UserPreferences
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPreferences
     */
    timezone?: string;
    /**
     * 
     * @type {NotificationSettings}
     * @memberof UserPreferences
     */
    notifications?: NotificationSettings;
    /**
     * 
     * @type {PrivacySettings}
     * @memberof UserPreferences
     */
    privacy?: PrivacySettings;
}


/**
 * @export
 */
export const UserPreferencesThemeEnum = {
    Light: 'light',
    Dark: 'dark',
    System: 'system'
} as const;
export type UserPreferencesThemeEnum = typeof UserPreferencesThemeEnum[keyof typeof UserPreferencesThemeEnum];


/**
 * Check if a given object implements the UserPreferences interface.
 */
export function instanceOfUserPreferences(value: object): value is UserPreferences {
    return true;
}

export function UserPreferencesFromJSON(json: any): UserPreferences {
    return UserPreferencesFromJSONTyped(json, false);
}

export function UserPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferences {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'] == null ? undefined : json['theme'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'notifications': json['notifications'] == null ? undefined : NotificationSettingsFromJSON(json['notifications']),
        'privacy': json['privacy'] == null ? undefined : PrivacySettingsFromJSON(json['privacy']),
    };
}

export function UserPreferencesToJSON(json: any): UserPreferences {
    return UserPreferencesToJSONTyped(json, false);
}

export function UserPreferencesToJSONTyped(value?: UserPreferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'theme': value['theme'],
        'language': value['language'],
        'timezone': value['timezone'],
        'notifications': NotificationSettingsToJSON(value['notifications']),
        'privacy': PrivacySettingsToJSON(value['privacy']),
    };
}

