/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileSocialLinks } from './UserProfileSocialLinks';
import {
    UserProfileSocialLinksFromJSON,
    UserProfileSocialLinksFromJSONTyped,
    UserProfileSocialLinksToJSON,
    UserProfileSocialLinksToJSONTyped,
} from './UserProfileSocialLinks';

/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    location?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfile
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {UserProfileSocialLinks}
     * @memberof UserProfile
     */
    socialLinks?: UserProfileSocialLinks | null;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'website': json['website'] == null ? undefined : json['website'],
        'location': json['location'] == null ? undefined : json['location'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'socialLinks': json['socialLinks'] == null ? undefined : UserProfileSocialLinksFromJSON(json['socialLinks']),
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(value?: UserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'bio': value['bio'],
        'website': value['website'],
        'location': value['location'],
        'birthDate': value['birthDate'] == null ? value['birthDate'] : value['birthDate'].toISOString().substring(0,10),
        'socialLinks': UserProfileSocialLinksToJSON(value['socialLinks']),
    };
}

