/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionResponse
 */
export interface VersionResponse {
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    version?: string;
    /**
     * 
     * @type {Date}
     * @memberof VersionResponse
     */
    buildDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    gitCommit?: string;
}

/**
 * Check if a given object implements the VersionResponse interface.
 */
export function instanceOfVersionResponse(value: object): value is VersionResponse {
    return true;
}

export function VersionResponseFromJSON(json: any): VersionResponse {
    return VersionResponseFromJSONTyped(json, false);
}

export function VersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'buildDate': json['buildDate'] == null ? undefined : (new Date(json['buildDate'])),
        'gitCommit': json['gitCommit'] == null ? undefined : json['gitCommit'],
    };
}

export function VersionResponseToJSON(json: any): VersionResponse {
    return VersionResponseToJSONTyped(json, false);
}

export function VersionResponseToJSONTyped(value?: VersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'buildDate': value['buildDate'] == null ? value['buildDate'] : value['buildDate'].toISOString(),
        'gitCommit': value['gitCommit'],
    };
}

