/* tslint:disable */
/* eslint-disable */
/**
 * Mock-Fried Sample API
 * Comprehensive sample API for testing mock-fried module
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdvancedOrder,
  AdvancedOrderListResponse,
  AllScalarTypes,
  CommentThread,
  Company,
  GraphNode,
  OrgMember,
  TreeNode,
  UserPreferences,
} from '../models/index';
import {
    AdvancedOrderFromJSON,
    AdvancedOrderToJSON,
    AdvancedOrderListResponseFromJSON,
    AdvancedOrderListResponseToJSON,
    AllScalarTypesFromJSON,
    AllScalarTypesToJSON,
    CommentThreadFromJSON,
    CommentThreadToJSON,
    CompanyFromJSON,
    CompanyToJSON,
    GraphNodeFromJSON,
    GraphNodeToJSON,
    OrgMemberFromJSON,
    OrgMemberToJSON,
    TreeNodeFromJSON,
    TreeNodeToJSON,
    UserPreferencesFromJSON,
    UserPreferencesToJSON,
} from '../models/index';

export interface GetAdvancedOrderRequest {
    id: string;
}

export interface GetCommentThreadRequest {
    id: string;
}

export interface GetCompanyRequest {
    id: string;
}

export interface GetGraphRequest {
    id: string;
}

export interface GetOrgChartRequest {
    id: string;
}

export interface GetTreeNodeRequest {
    id: string;
}

export interface ListAdvancedOrdersRequest {
    page?: number;
    limit?: number;
}

export interface UpdateUserPreferencesRequest {
    userPreferences: UserPreferences;
}

/**
 * 
 */
export class AdvancedCasesApi extends runtime.BaseAPI {

    /**
     * Get order with nested enum
     */
    async getAdvancedOrderRaw(requestParameters: GetAdvancedOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdvancedOrder>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAdvancedOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/orders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdvancedOrderFromJSON(jsonValue));
    }

    /**
     * Get order with nested enum
     */
    async getAdvancedOrder(requestParameters: GetAdvancedOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdvancedOrder> {
        const response = await this.getAdvancedOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all scalar types (Proto3 feature testing)
     */
    async getAllScalarTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllScalarTypes>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/scalars`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllScalarTypesFromJSON(jsonValue));
    }

    /**
     * Get all scalar types (Proto3 feature testing)
     */
    async getAllScalarTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllScalarTypes> {
        const response = await this.getAllScalarTypesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get comment thread (recursive)
     */
    async getCommentThreadRaw(requestParameters: GetCommentThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentThread>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCommentThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/comment-thread/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentThreadFromJSON(jsonValue));
    }

    /**
     * Get comment thread (recursive)
     */
    async getCommentThread(requestParameters: GetCommentThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentThread> {
        const response = await this.getCommentThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get company with deep nesting
     */
    async getCompanyRaw(requestParameters: GetCompanyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Company>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCompany().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/company/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyFromJSON(jsonValue));
    }

    /**
     * Get company with deep nesting
     */
    async getCompany(requestParameters: GetCompanyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Company> {
        const response = await this.getCompanyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get graph node (recursive with edges)
     */
    async getGraphRaw(requestParameters: GetGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphNode>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGraph().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/graph/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GraphNodeFromJSON(jsonValue));
    }

    /**
     * Get graph node (recursive with edges)
     */
    async getGraph(requestParameters: GetGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphNode> {
        const response = await this.getGraphRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get organization chart (recursive)
     */
    async getOrgChartRaw(requestParameters: GetOrgChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgMember>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrgChart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/org-chart/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgMemberFromJSON(jsonValue));
    }

    /**
     * Get organization chart (recursive)
     */
    async getOrgChart(requestParameters: GetOrgChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgMember> {
        const response = await this.getOrgChartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get tree node (recursive structure)
     */
    async getTreeNodeRaw(requestParameters: GetTreeNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeNode>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTreeNode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/tree/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeNodeFromJSON(jsonValue));
    }

    /**
     * Get tree node (recursive structure)
     */
    async getTreeNode(requestParameters: GetTreeNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeNode> {
        const response = await this.getTreeNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user preferences (optional fields)
     */
    async getUserPreferencesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPreferences>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/preferences`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPreferencesFromJSON(jsonValue));
    }

    /**
     * Get user preferences (optional fields)
     */
    async getUserPreferences(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPreferences> {
        const response = await this.getUserPreferencesRaw(initOverrides);
        return await response.value();
    }

    /**
     * List orders with nested enum (page pagination)
     */
    async listAdvancedOrdersRaw(requestParameters: ListAdvancedOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdvancedOrderListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/advanced/orders`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdvancedOrderListResponseFromJSON(jsonValue));
    }

    /**
     * List orders with nested enum (page pagination)
     */
    async listAdvancedOrders(requestParameters: ListAdvancedOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdvancedOrderListResponse> {
        const response = await this.listAdvancedOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update user preferences
     */
    async updateUserPreferencesRaw(requestParameters: UpdateUserPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPreferences>> {
        if (requestParameters['userPreferences'] == null) {
            throw new runtime.RequiredError(
                'userPreferences',
                'Required parameter "userPreferences" was null or undefined when calling updateUserPreferences().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/advanced/preferences`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserPreferencesToJSON(requestParameters['userPreferences']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPreferencesFromJSON(jsonValue));
    }

    /**
     * Update user preferences
     */
    async updateUserPreferences(requestParameters: UpdateUserPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPreferences> {
        const response = await this.updateUserPreferencesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
